Fix ExitOnIdleService failing when cysystemd is used
It failed with:

      File "/lib/python3.12/site-packages/gdbus_util/exit_on_idle.py", line 207, in run
        systemd_daemon.notify("STOPPING=1")
      File "/lib/python3.12/site-packages/cysystemd/daemon.py", line 53, in notify
        raise TypeError("state must be an instance of Notification")
    TypeError: state must be an instance of Notification